apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  selector:
    matchLabels:
      app: fastapi-deployment
  template:
    metadata:
      labels:
        app: fastapi-deployment
    spec:
      containers:
        - name: fastapi-deployment
          image: demo.goharbor.io/trivy/test
          ports:
          - name: http
            containerPort: 8000
            protocol: TCP