apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trivy-ci-base
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ermvipul/trivy-ci-base
    targetRevision: main
    path: kustomize/base

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
